// Generate "sprites" -  single file which contains
// many icons inside, Goal - reduce images download
// time for client's browsers
// Steps:
// 1. Take all individual  files
// 2. Run gulp-svg-sprite plugin to pack them into
//   one SVG XML file.

var gulp = require('gulp'),
    svgSprite = require('gulp-svg-sprite'),
    rename = require('gulp-rename'),
    del = require('del');

// Configuration object for the plugin
// Generates CSS file with positions and offsets
// for every icon.
//
var config = {
  mode: {
    css: {
      sprite: 'sprite.svg',
      render: {
        css: {
          template: './gulp/templates/sprite.css'
        }
      }
    }
  }
}

// Begin Clean of temp folders from previous run
// Goal: to avoid growing number of old sprite-xxxx.svg files in folder.
//       guarantee clean environment for new sprite file generation
gulp.task('beginClean', function() {
  return del(['./app/temp/sprite', './app/assets/images/sprites']);
});

// Generate new sprite file according to config object ,
//    and template file
gulp.task('createSprite',['beginClean'], function() {
  return gulp.src('./app/assets/images/icons/**/*.svg')
    .pipe(svgSprite(config))
    .pipe(gulp.dest('./app/temp/sprite'));
});
// Copy .svg file with icons, generated by createSprite
gulp.task('copySpriteGraphic',['createSprite'], function() {
    return gulp.src('./app/temp/sprite/css/**/*.svg')
      .pipe(gulp.dest('./app/assets/images/sprites'));
});
// Copy created Sprite CSS file into centralized location
gulp.task('copySpriteCSS',['createSprite'], function() {
  return gulp.src('./app/temp/sprite/css/*.css')
    .pipe(rename('_sprite.css'))
    .pipe(gulp.dest('./app/assets/styles/modules'));
});

// End Clean  to remove tmp directory: ./app/temp/sprite
gulp.task('endClean',['copySpriteGraphic','copySpriteCSS'], function() {
  return del('./app/temp/sprite');
});

// Run Icon Sprite generation and distribution to directory tree
gulp.task('icons', ['beginClean','createSprite','copySpriteGraphic','copySpriteCSS','endClean']);
